version: '3.7'

volumes:
        elmos-database:
        elmos-redis:

services:
        elmos:
                image: elmos:latest
                build:
                        context: ./microservices/app/
                        dockerfile: ./Dockerfile
                container_name: ${PROJECT_BASENAME}-app
                restart: always
                environment:
                        DB_USER: ${DB_USER}
                        DB_PASS: ${DB_PASS}
                        DB_DATABASE: ${DB_DATABASE}
                        SECRET_KEY: ${SECRET_KEY}
                ports:
                        - ${UI_PORT}:80
                depends_on:
                        - db
                        - redis
        db:
                image: mariadb
                container_name: ${PROJECT_BASENAME}-db
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
                        MYSQL_USER: ${DB_USER}
                        MYSQL_PASSWORD: ${DB_PASS}
                        MYSQL_DATABASE: ${DB_DATABASE}
                volumes:
                        - elmos-database:/var/lib/mysql
                        - "/etc/timezone:/etc/timezone:ro"
                        - "/etc/localtime:/etc/localtime:ro"
        redis:
                image: redis
                container_name: ${PROJECT_BASENAME}-redis
                restart: always
                volumes:
                        - elmos-redis:/data
        dbwriter2:
                image: elmosdbwriter2:latest
                build:
                        context: ./microservices/dbwriter2/
                        dockerfile: ./Dockerfile
                container_name: ${PROJECT_BASENAME}-dbwriter2
                restart: always
                environment:
                        DB_USER: ${DB_USER}
                        DB_PASS: ${DB_PASS}
                        DB_DATABASE: ${DB_DATABASE}
                ports:
                        - 127.0.0.1:${DBWRITER_PORT}:80
                depends_on:
                        - db
                        - redis
        golman:
                image: golman:latest
                build:
                        context: ./microservices/golman/
                        dockerfile: ./Dockerfile
                container_name: ${PROJECT_BASENAME}-golman
                restart: always
                environment:
                        EDU_DOMAIN: ${EDU_DOMAIN}
                        EDU_USER: ${EDU_USER}
                        EDU_PASS: ${EDU_PASS}
                        EDU_TERM: ${EDU_TERM}
                        GOLMAN_SLEEP: ${GOLMAN_SLEEP}
                depends_on:
                        - dbwriter2
                        - elmos
