version: '3.7'

services:
        elmos-green:
                image: elmos:latest
                build:
                        context: ./microservices/app/
                        dockerfile: ./Dockerfile
                container_name: elmos-app-green
                restart: always
                environment:
                        DB_USER: ${DB_USER}
                        DB_PASS: ${DB_PASS}
                        DB_DATABASE: ${DB_DATABASE}
                        SECRET_KEY: ${SECRET_KEY}
                ports:
                        - ${UI_PORT_GREEN}:80
