version: '3.7'

volumes:
        elmos-database:
        elmos-redis:

services:
        elmos:
                image: elmos:latest
                build:
                        context: ./microservices/app/
                        dockerfile: ./Dockerfile
                container_name: elmos-app
                restart: always
                environment:
                        DB_USER: ${DB_USER}
                        DB_PASS: ${DB_PASS}
                        DB_DATABASE: ${DB_DATABASE}
                ports:
                        - ${UI_PORT}:80
                volumes:
                        - .:/var/www/elmos
                depends_on:
                        - db
                        - redis
        db:
                image: mariadb
                container_name: elmos-db
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
                        MYSQL_USER: ${DB_USER}
                        MYSQL_PASSWORD: ${DB_PASS}
                        MYSQL_DATABASE: ${DB_DATABASE}
                volumes:
                        - elmos-database:/var/lib/mysql
        redis:
                image: redis
                container_name: elmos-redis
                restart: always
                volumes:
                        - elmos-redis:/data
        dbwriter:
                image: elmosdbwriter:latest
                build:
                        context: ./microservices/dbwriter/
                        dockerfile: ./Dockerfile
                container_name: elmos-dbwriter
                restart: always
                environment:
                        DB_USER: ${DB_USER}
                        DB_PASS: ${DB_PASS}
                        DB_DATABASE: ${DB_DATABASE}
                ports:
                        - 127.0.0.1:${DBWRITER_PORT}:91
                depends_on:
                        - db
                        - redis

