version: '3.7'

volumes:
        elmos-database:

services:
        elmos:
                image: elmos:latest
                build:
                        context: .
                        dockerfile: ./Dockerfile
                container_name: elmos-app
                restart: always
                environment:
                        DB_USER: ${DB_USER}
                        DB_PASS: ${DB_PASS}
                        DB_DATABASE: ${DB_DATABASE}
                ports:
                        - ${UI_PORT}:80
                volumes:
                        - .:/var/www/elmos
        db:
                image: mariadb
                container_name: elmos-db
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
                        MYSQL_USER: ${DB_USER}
                        MYSQL_PASSWORD: ${DB_PASS}
                        MYSQL_DATABASE: ${DB_DATABASE}
                volumes:
                        - elmos-database:/var/lib/mysql
